---
title: "Simplest Model Validation"
author: "Shawn Garbett"
date: "9/16/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("simple-params.R")
source("simple-des.R")
source("simple-deq.R")

```

## Visual comparison of DES and DiffEq

Comparison of DES and Diff Eq solutions to simplest model.

```{r compare}
des <- des_simulation(params)
deq <- deq_simulation(params)


par(mfrow=c(1,2))
# Overlay Indicate by DES and DEQ
plot(deq[,'time'], deq[,'a_c'], type='l', lwd=2, ylab='Population Ratio', xlab="t (year)", main="Total Indication")
ind.ordered <- sort(des$indication)
sub <- seq(1, length(ind.ordered), by=1000)
lines(ind.ordered[sub]/365, sub/params$n, col='red', lty=2, lwd=2)

# Let's look at A disutility occupancy
plot(deq[,'time'], rowSums(deq[,c('a_dp','a_da')]), type='l', lwd=2, ylab='Population Ratio', xlab="t (year)",
     main="Indication Disutility")

x <- data.frame(time=c(des$indication, des$cutoff),
                count=c(rep(1,  length(des$indication)),
                        rep(-1, length(des$cutoff))))
x <- x[order(x$time,na.last=NA),]
x$count <- cumsum(x$count)
lines(x$time/365, x$count/params$n, col='red', lty=2)

par(mfrow=c(1,2))
plot(deq[,'time'], rowSums(deq[,c('a_p','a_a')]), type='l', lwd=2, ylab='Population Ratio', xlab="t (year)", main="Indication Occupancy")
end_of_ind <- pmin(des$adverse, des$death, na.rm=TRUE)
end_of_ind[is.na(des$indication)] <- NA
x <- data.frame(time=c(des$indication, end_of_ind),
                count=c(rep(1,  length(des$indication)),
                        rep(-1, length(end_of_ind))))
x <- x[order(x$time,na.last=NA),]
x$count <- cumsum(x$count)
lines(x$time/365, x$count/params$n, col='red', lty=2)

plot(deq[,'time'], deq[,'b_d'], type='l', lwd=2, ylab='Population Ratio', xlab="t (year)", main="Adverse Deaths")

adv.deaths <- sort(des$adverse_death[!is.na(des$adverse_death)])
sub <- seq(1, length(adv.deaths), by=10)
lines(adv.deaths[sub]/365, sub/params$n, col='red', lty=2, lwd=2)
```

## Compare End Results


```{r results}
rbind(des=des_summary(des, params),
      deq=deq_summary(deq, params))
```


