event_registry <- list(
  list(name          = "Secular Death", 
  attr          = "aSecularDeathTime", 
  time_to_event = days_till_death,  
  func          = secular_death,  
  reactive      = FALSE),  

                                  	 list(name          = "Event A_SC_A",
                                  	 	 attr          = "attA_SC_A",
                                  	 time_to_event = days_till_A_SC_A,
                                  	 	 func          = event_A_SC_A,
                                  	 	 reactive      = FALSE),
                                  	 list(name          = "Event B_SC_A",
                                  	 	 attr          = "attB_SC_A",
                                  	 	 time_to_event = days_till_B_SC_A,
                                  	 	 func          = event_B_SC_A,
                                  	 	 reactive      = FALSE),
                                   
                                  	 list(name          = "Event A_SC_B",
                                  	 	 attr          = "attA_SC_B",
                                  	 time_to_event = days_till_A_SC_B,
                                  	 	 func          = event_A_SC_B,
                                  	 	 reactive      = FALSE),
                                  	 list(name          = "Event B_SC_B",
                                  	 	 attr          = "attB_SC_B",
                                  	 	 time_to_event = days_till_B_SC_B,
                                  	 	 func          = event_B_SC_B,
                                  	 	 reactive      = FALSE),
                                   
                                  	 list(name          = "Event A_SC_C",
                                  	 	 attr          = "attA_SC_C",
                                  	 time_to_event = days_till_A_SC_C,
                                  	 	 func          = event_A_SC_C,
                                  	 	 reactive      = FALSE),
                                  	 list(name          = "Event B_SC_C",
                                  	 	 attr          = "attB_SC_C",
                                  	 	 time_to_event = days_till_B_SC_C,
                                  	 	 func          = event_B_SC_C,
                                  	 	 reactive      = FALSE),
                                   
                                  	 list(name          = "Event A_SC_D",
                                  	 	 attr          = "attA_SC_D",
                                  	 time_to_event = days_till_A_SC_D,
                                  	 	 func          = event_A_SC_D,
                                  	 	 reactive      = FALSE),
                                  	 list(name          = "Event B_SC_D",
                                  	 	 attr          = "attB_SC_D",
                                  	 	 time_to_event = days_till_B_SC_D,
                                  	 	 func          = event_B_SC_D,
                                  	 	 reactive      = FALSE),
                                    list(name          = "Terminate at time horizonb",
  	 	 attr          = "aTerminate",
  	 	 time_to_event = function(attrs,inputs) 365.0*inputs$vHorizon,
  	 	 func          = terminate_simulation,
  	 	reactive      = FALSE)
) 
